services:
  - type: web
    name: summary-generator-backend
    env: node
    rootDir: server
    buildCommand: |
      pip install -r requirements.txt
      npm install
    startCommand: node index.js
